### ISSUE TITLE
Getting error "You are not authorized to perform this operation" when CodeBuild runs 'npx cdk synth'

### ISSUE THREAD

**Issue by franccan** [aws/meta-aws-ci#10]
The issue goes away when I manually add the permission “ec2:DescribeAvailabilityZones” to the ” IAM role that starts with ‘GreengrassDeviceImageBuil-PipelineBuildSynthCdk’ 

There is some information about similar behaviour here: 
- https://github.com/aws/aws-cdk/issues/2643
- https://stackoverflow.com/questions/56483906/codebuild-failing-to-run-cdk-synth

**Comment by rpcme** [comment]
@franccan can you give me a code permalink for this issue in our code or can you do a pull request if this is working?

**Comment by rpcme** [comment]
CDK project has been deprecated
