### ISSUE TITLE
Getting error: Error calling startBuild: Cannot have more than 0 builds in queue for the account:

### ISSUE THREAD

**Issue by franccan** [aws/meta-aws-ci#12]
It seems that my account is hitting a limit on the number of running vCPUs. The reference implementation uses the largest instance available (145 GB , 72 vCPUs). Using a smaller instance allows me to build the project.

Suggested modifications to: ‘cdk/lib/stacks/yocto-image-builder-stack.ts’ so that the process will not fail on accounts which may be hitting a limit.

```js
...
import { Construct, SecretValue, Stack, StackProps, RemovalPolicy, Duration } from '@aws-cdk/core';
...
const buildProject = new codebuild.PipelineProject(this, `YoctoBuild-${machineType}-${projectType}-${yoctoProjectRelease}`, {
   ...
    timeout: Duration.hours(8)
    ...
    environment: {
        ...
        computeType: codebuild.ComputeType.LARGE,
        ...
    },
   ...
});

```

**Comment by rpcme** [comment]
@franccan is there a code pipeline facility that enables this kind of behavior? Can you send a doc pointer?

**Comment by rpcme** [comment]
CDK project has been deprecated
