### ISSUE TITLE
"rpi_foundation" missing from manifest path in 'hardknott' & 'gatesgarth' release

### ISSUE THREAD

**Issue by franccan** [aws/meta-aws-ci#13]
Error logs from CodeBuild
```log
[Container] 2021/08/09 20:39:45 Running command git config --global user.email "email@example.com"
43 |  
44 | [Container] 2021/08/09 20:39:45 Phase complete: PRE_BUILD State: SUCCEEDED
45 | [Container] 2021/08/09 20:39:45 Phase context status code:  Message:
46 | [Container] 2021/08/09 20:39:45 Entering phase BUILD
47 | [Container] 2021/08/09 20:39:45 Running command curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/repo
48 | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
49 | Dload  Upload   Total   Spent    Left  Speed
50 |  
51 | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
52 | 100 44704  100 44704    0     0  1984k      0 --:--:-- --:--:-- --:--:-- 1984k
53 |  
54 | [Container] 2021/08/09 20:39:45 Running command chmod +x $HOME/repo
55 |  
56 | [Container] 2021/08/09 20:39:45 Running command mkdir $HOME/dist
57 |  
58 | [Container] 2021/08/09 20:39:45 Running command cd $HOME/dist
59 |  
60 | [Container] 2021/08/09 20:39:45 Running command $HOME/repo init -u https://github.com/aws-samples/meta-aws-demos -m raspberrypi4-64/aws-iot-greengrass-v2/hardknott/repo.xml
61 | Downloading manifest from https://github.com/aws-samples/meta-aws-demos
62 | fatal: manifest 'raspberrypi4-64/aws-iot-greengrass-v2/hardknott/repo.xml' not available
63 | fatal: manifest raspberrypi4-64/aws-iot-greengrass-v2/hardknott/repo.xml not found
64

<br class="Apple-interchange-newline">

```

Files that need to be reviewed:

https://github.com/aws-samples/meta-aws-demos/blob/master/rpi_foundation/rpi4-64/aws-iot-greengrass-v2/hardknott/buildspec.yml#L24

https://github.com/aws-samples/meta-aws-demos/blob/master/rpi_foundation/rpi4-64/aws-iot-greengrass-v2/gatesgarth/buildspec.yml#L25

Reference file that works ok:

https://github.com/aws-samples/meta-aws-demos/blob/master/rpi_foundation/rpi4-64/aws-iot-greengrass-v2/gatesgarth/buildspec.yml#L25

**Comment by philcali** [comment]
This is actually a `meta-aws-demos` fix... I did one for dunfell here: https://github.com/aws-samples/meta-aws-demos/commit/6c1eacc4d5c45d7e622a1597ff56a4352160b201

**Comment by philcali** [comment]
An idea: the `buildspec` is actually a template that is expanded based on `bspType` parameter for the image builder stack. This would handle some of the redundancy, but it risks making a specific bsp build being a little more difficult.

**Comment by franccan** [comment]
https://github.com/aws-samples/meta-aws-demos/pull/14

**Comment by rpcme** [comment]
Fixed in meta-aws-demos - closing.
