### ISSUE TITLE
Yoctoproject's meta-java doesn't have a hardknott branch

### ISSUE THREAD

**Issue by MassimoSporchia** [aws/meta-aws-ci#18]
In "Step 3 - Integrate layers and your application layer" where there's the clone of the repositories step, yocto's meta-java still doesn't have a hardknott branch ( https://git.yoctoproject.org/cgit/cgit.cgi/meta-java/refs/ ).

It works, but it is currently referencing a master's specific commit.
Reference: https://github.com/aws/meta-aws-ci/blob/master/workshop/content/03_modules/01_hello_yocto/_index.md#step-3---integrate-layers-and-your-application-layer

To-do: fix as soon as they create the branch

**Comment by rpcme** [comment]
I think the question is @MassimoSporchia why are we using meta-java?  I think perhaps that should be removed in lieu of using Corretto if needed?

**Comment by rpcme** [comment]
Per massimo this will be removed from the workshop
