### ISSUE TITLE
Add ci_image folder back

### ISSUE THREAD

**Issue by franccan** [aws/meta-aws-ci#9]
The folder is required to build the docker container that is used to build images:
https://github.com/aws/meta-aws-ci/blob/master/buildspec/ci_image.yml#L13 

Also, the customised Dockerfile has Yocto-specific modifications:
https://github.com/aws/meta-aws-ci/blob/51436380ede729b62d68c966a4acff3f9c3a05e5/ci_image/Dockerfile#L183

**Comment by rpcme** [comment]
@franccan I need to deprecate this directory.  the directories are under core/ now. The main reason I will be building additional container images required for other BSPs that need different toolchains.  For Cloudformation, I think it's all set.  Is the issue in the CDK?

**Comment by franccan** [comment]
There are two issues:

1.	`GithubBaseImageRepositorySpecLocation` in `prerequisites-stack.ts` would need to be updated to match the location of the buildspec file. **(but this may not be needed, look at issue No.2)**

2.	CodeDeploy seems to be picky about the location and name of the buildspec file. It seems that the file cannot be in an arbitrary location with arbitrary name.  The docs do _not_ mention this specifically, it may be an issue with CodeDeploy https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

Error when the file sits in `core/buildspec/ci_image.yml` (and GithubBaseImageRepositorySpecLocation pointing to it):
```
[Container] 2021/08/13 09:43:14 Waiting for agent ping
[Container] 2021/08/13 09:43:17 Waiting for DOWNLOAD_SOURCE
[Container] 2021/08/13 09:43:18 Phase is DOWNLOAD_SOURCE
[Container] 2021/08/13 09:43:18 CODEBUILD_SRC_DIR=/codebuild/output/src395347404/src
[Container] 2021/08/13 09:43:18 YAML location is /codebuild/output/src395347404/src/core/buildspec/ci_image.yml
[Container] 2021/08/13 09:43:18 Phase complete: DOWNLOAD_SOURCE State: FAILED
[Container] 2021/08/13 09:43:18 Phase context status code: YAML_FILE_ERROR Message: wrong number of container tags, expected 1
```
Moving the file back to `buildspec/ci_image.yml`  works without issues:

```
[Container] 2021/08/13 10:15:52 Waiting for agent ping
[Container] 2021/08/13 10:15:55 Waiting for DOWNLOAD_SOURCE
[Container] 2021/08/13 10:15:56 Phase is DOWNLOAD_SOURCE
[Container] 2021/08/13 10:15:56 CODEBUILD_SRC_DIR=/codebuild/output/src587018348/src
[Container] 2021/08/13 10:15:56 YAML location is /codebuild/output/src587018348/src/buildspec/ci_image.yml
[Container] 2021/08/13 10:15:56 Processing environment variables
```

**Comment by rpcme** [comment]
1/ This is codebuild, not codedeploy
2/ I don't know why we are facing this buildspec issue because the yocto image build process has an arbitrary location

**Comment by rpcme** [comment]
CDK project has been deprecated
